version: "3.3"
services:
  psql:
    image: postgres
    container_name: postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: tasker_db

volumes:
  postgresql_data: